labmachine:
  tags: [labmachine]
  timeout: 20h
  stage: deploy
  image: registry.letsboot.com/lib/labmachine-core/labmachine:$LAB_IMAGE_TAG
  variables:
    LAB_CODESERVER_DIR: $CI_PROJECT_DIR
    LAB_IDENTITY: $CI_JOB_ID
    LAB_GITLAB_TOKEN: $GITLAB_CI_PROJECT_TOKEN
    # disabled for now, as there are no chapters depending on it
    LAB_ENABLE_PROMETHEUS_GRAFANA: "false"
    LAB_ENABLE_ARGOCD: "false"
    LAB_ENABLE_GITLAB_ARGOCD: "false"
    # activate variables vor DevOps example
    #LAB_ENABLE_GITLAB_KUBECONFIG: "false"
    #LAB_ENABLE_KIND: "false"
    #LAB_ENABLE_METRICS_SERVER: "false"
    #LAB_ENABLE_NGINX_INGRESS: "false"
    #LAB_ENABLE_CILIUM: "false"
    # has to be shorter than the project ci/cd timeout, so the job doesn't fail
    LAB_SLEEP: 71000
  allow_failure: true
  script:
    - lab_start.sh
    - >
      [ "$CUSTOM_INIT" == "true" ] && (/bin/bash .labmachine/custom-init.sh > /labmachine/logs/custom-init.log 2>&1 || cat /labmachine/logs/custom-init.log)
    - sleep ${LAB_SLEEP}
  after_script:
    - |
      if [ "$CI_JOB_STATUS" != "success" ] && [ "$PARENT_PIPELINE_SOURCE" == "web" ]; then \
        echo "Failure. I'll give you some time to investigate."
        sleep 360
      fi
  rules:
    - if: $LAB_START == "default"

labmachine-desktop:
  extends: labmachine
  image: registry.letsboot.com/lib/labmachine-core/labmachine-kasmvnc:$LAB_IMAGE_TAG
  variables:
    LAB_ENABLE_KASMVNC: "true"
  rules:
    - if: $LAB_START == "desktop"